### ISSUE TITLE
[Feature Request] Serial_CRC.pnach instead of CRC.pnach

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2_patches#10] opened 2022-11-19 18:38 UTC
To mimic what the inis use:
![image](https://user-images.githubusercontent.com/24227051/202866377-4c6787c5-8199-4612-8379-352064bf21ed.png)

As it triggers CRC collisions
[7ACF7E03.txt](https://github.com/PCSX2/pcsx2_patches/files/10047722/7ACF7E03.txt)

It would also make it easier to seek serials and avoid more typos.

**Comment by AfterDyons** [comment] 2022-11-20 14:44
Pnach that you have posted works only when TMB's ELF file is loaded into memory
There is no reason to rename all pnaches when a few cheat codes collisions can be easily fixed in pnach file

**Comment by Mrlinkwii** [comment] 2022-11-28 11:26
@AfterDyons  the issue is around CRC collision ( ehich is rare)

**Comment by refractionpcsx2** [comment] 2023-05-24 14:44
Please post this as a request on the PCSX2 repo not the patches one, then we can deal with it on that end.

**Closed by refractionpcsx2** 2023-05-24 14:44 UTC

**Comment by mirh** [comment] 2023-05-25 08:49
I could also find some consideration about collisions in https://github.com/PCSX2/pcsx2/issues/5062

Anyway, I can see how you may be looking at this from an "implementation" pov, but I believe this is *also* a design conundrum (of the repository, I mean.. since you have to rename all files). 
Like, anything that could un-uglify the current flat structure with thousands of files should be welcomed (as I noted [once](https://github.com/PCSX2/pcsx2/pull/2537) when the idea was first proposed).
